defaultSemverRangePrefix: ''

nodeLinker: node-modules

npmAlwaysAuth: true
npmAuthToken: PRIVATE-TOKEN-1
npmRegistryServer: 'https://artifactory.example.com/npm/registry1'

npmScopes:
  foobar:
    npmAlwaysAuth: true
    npmAuthToken: PRIVATE-TOKEN-2
    npmRegistryServer: 'https://artifactory.example.com/npm/registry2'

pnpEnableEsmLoader: false

yarnPath: .yarn/releases/yarn-3.2.1.cjs
